### PR TITLE
Create LndSwaggetClient on compile time with NSwag

### PR DESCRIPTION
**Pull request by joemphilips**
* So that bumping the LndSwaggerClient version will be half-automatic.
* do not include `LndSwaggerClient.cs` into version checking.
  * Since we don't want to allow someone to manually edit it anymore.

### CODE REVIEW

**Comment by joemphilips** [comment]
Ready for review.
I need this to use some new features of the LND (namely, hodl invoice).
Bumping the version should now be simple enough to just edit the `LndVersion` section of `BTCPayServer.Lightning.LND.csproj`.

**Comment by NicolasDorier** [comment]
I don't think that's a good idea.
1. Are you sure there is no breaking change?
2. Automatic clients are problematic, because it suppose that we run on a specific version of the server.

For example https://github.com/btcpayserver/BTCPayServer.Lightning/pull/47/files#diff-a850aaf087776e2c89d340a38556c240830d0ee3e0a9b761aac0a4aa3a8cd754R432

What if this is run on a LND which doesn't know `Type.WITNESS_PUBKEY_HASH` (because it did not existed before).
Might be OK, but the fact that we test one version only mean we need to be even more careful to this type of change.

I think people who need the swagger client can just generate it in their project and don't really need this library.
The advantage of this library is the common abstraction, and the fact we do our best to work on several versions of LND, despite the breaking changes they are making.

**Comment by joemphilips** [comment]
> 1. Are you sure there is no breaking change?

I'm not 100% sure. I thought passing the test is good enough.
That is because I did not know what is the original version of the swagger.json from which `LndSwaggerClient` is generated. 

> 2. Automatic clients are problematic, because it suppose that we run on a specific version of the server.

This is true even for the current codebase, isn't it? `LndSwaggerClient.cs` is automatically generated and untouched. Abstraction is done in the different files.


> I think people who need the swagger client can just generate it in their project and don't really need this library.
The advantage of this library is the common abstraction, with some useful type rather than primitive types and the fact we do our best to work on several versions of LND, despite the breaking changes they are making.

This is fair point and I'm not against it. (In fact I've been switching to generate it in my own library.)
But I believe automating the generation helps this codebase too. Even if you have no plan to bump the Swagger version, it is clear to everyone how the SwaggerClient is generated and what version of the `swagger.json` it originates.

Think this PR is just for a documentation and it is not intended to change the actual codebase in anyway, it has slightly changed because I had no way to know the original version of `LndSwaggerClient`. (and that is the exactly a problem it is trying to solve.)

**Comment by joemphilips** [comment]
> it has slightly changed it because I had no way to know the original version of LndSwaggerClient.

Give me
1. version of the `swagger.json`
2. `nswag.json`
 
you used to generated current `LndSwaggerClient` , if you don't want to change the behavior of the client in any way. I can used the same in this PR.

**Comment by NicolasDorier** [comment]
Generated by `"NSwag", "11.11.1.0"` the 8/29/2018 

There has been some manual change to the code as you can see in the history of the file.
The way I know that the current code works on several version is because I never re-generated the client, I instead manually edited the file to fix the gaps along the way. (only focusing on what is useful for shared abstraction)

I think we could generate a new `LndSwaggerClient` but I'd like to see the code diff, so we are sure we don't break something.
We should not run the tool silently during the build process.

I see the value in doing that, where at least we can know, as you said, from which swagger file the code has been generated, and it simplify bumping the version. (we just have to review the generated code don't break things)

**Comment by DocBrown101** [comment]
Is there a decision on how to proceed? You can simply continue with a higher "main" version.

**Comment by NicolasDorier** [comment]
I am still undecided on this one. I don't like fixing something that isn't broken, if somebody need the full power of LND, I don't think there is lot's of advantage to use this library, they can just make the swagger client by themselves.

There is value to make the dev of the lnd client more easy to maintain. But I can't say this library really require much maintenance anyway.

**Comment by dennisreimann** [comment]
I'll close this, as we've proceeded with manually adding new features and this works well for now. I'd be fine with re-evaluating the autogenerate approach once bigger changes come up.

**Pull request closed without merging**
