### PR TITLE
LightMoney: Fix unit for Satoshis initializer with long values

### PR DESCRIPTION
**Pull request by dennisreimann**

### CODE REVIEW

**Comment by NicolasDorier** [comment]
fuck no this need to be reverted

**Comment by NicolasDorier** [comment]
this is milli satoshi, not satoshi. The behavior is correct.

**Comment by NicolasDorier** [comment]
ah no its not

**Comment by dennisreimann** [comment]
[Non ? Si ! Oh !!!!](https://www.youtube.com/watch?v=r3FEhHF_fzM&feature=youtu.be&t=13) 😂

**Pull request merged**
