### PR TITLE
Ptarmigan Support

### PR DESCRIPTION
**Pull request by nayuta-kohei**
Added [Ptarmigan](https://github.com/nayutaco/ptarmigan) to BTCPayServer.Lightning.

Ptarmigan doker image is on the [Docker Hub](https://hub.docker.com/r/nayutaco/ptarmigan).

### CODE REVIEW

**Comment by NicolasDorier** [comment]
cool ! testing

**Comment by NicolasDorier** [comment]
Feedback (it is not blocking for this PR):

1. You should put the dockerfile in the ptarmigan repo instead of separate repo
2. You should use the nodejs docker base images
3. You should use multi stage build to decrease the size of image (you can check how I did on the RTL -ride the lightning- project)

**Comment by NicolasDorier** [comment]
You really need to provide a better API for your invoice notifications.
The way you do will fail in production as soon as too much invoice have been created by your instance...

**Comment by nayuta-kohei** [comment]
@NicolasDorier 

Thank you for the feedback!
I believe that we need better API for the invoice notifications and we will work on it as soon as possible.

**Pull request merged**
