### PR TITLE
Update LND Client with new generated code from 0.10-beta.rc2

### PR DESCRIPTION
**Pull request by ysangkok**
I have only tested generating a seed and initializing a wallet. I could imagine that consumer usage could break since some classes have different fields now, but it would be too much work to fix LND's compatibilies in this library anyway. So I guess it is no big deal that this change API?

### CODE REVIEW

**Comment by Kukks** [comment]
We need to be backwards compatible, cannot just break everyone's install..

**Comment by ysangkok** [comment]
Who is using this? Then I could test.

**Comment by Kukks** [comment]
Every install of BTCPayServer deployed with LND :)

**Comment by ysangkok** [comment]
Which is the oldest supported LND version?

**Comment by NicolasDorier** [comment]
We can't reply to this question, if people deployed manually (and a lot does), then we can't assume the version they use. Need to keep backward compatibility.

**Comment by NicolasDorier** [comment]
What can be done though is a fallback: Try the new method, and if that fail, try the old one.

**Comment by ysangkok** [comment]
If a new Request class has an optional field that is not in the old API, the new API is still compatible. I was looking through the diff, but it is hard to read (one could try with the same NSwag version you used). From my cursory reading, I have yet to find a Response class which had a field removed. So it may be that the new API is backwards compatible on the API level.

But, if you do not assign one of the optional fields, and the class is serialized to have that field set to `null`, I would imagine that an old LND would reject it for containing an unknown key. When you say you want backward compatibility, I guess you want it on the protocol level.

Trying both ways would be doable by making the current Request class an Interface and letting the two implementations implement it. But I don't know of any automated ways of automatically making an Interface by inspecting the fields of two classes... It would be a lot easier to just make separate interfaces for every schema.

**Comment by NicolasDorier** [comment]
@ysangkok if you have a single field that you need or that change, you should do 1 code change specifically for this field instead of regenerating all.

**Pull request closed without merging**
